"""empty message

Revision ID: 129cdf5707ca
Revises: da9db80af79c
Create Date: 2016-08-19 16:26:14.411301

"""

# revision identifiers, used by Alembic.
revision = '129cdf5707ca'
down_revision = 'da9db80af79c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'user_id')
    ### end Alembic commands ###
