"""empty message

Revision ID: da9db80af79c
Revises: None
Create Date: 2016-08-19 13:52:39.558499

"""

# revision identifiers, used by Alembic.
revision = 'da9db80af79c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('status', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'status')
    ### end Alembic commands ###
