"""empty message

Revision ID: fe629f688702
Revises: None
Create Date: 2016-09-04 13:11:29.398796

"""

# revision identifiers, used by Alembic.
revision = 'fe629f688702'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    ### end Alembic commands ###
